name: Java CI

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Setup redis 1
        uses: getong/redis-action@v1
        with:
          redis version: '3.2.3'
          host port: 6380
          container port: 6380
          redis password: 'test'
      - name: Setup redis 2
        uses: shogo82148/actions-setup-redis@v1
        with:
          redis-version: '6.x'
      - uses: actions/checkout@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 1.8
          distribution: 'adopt'
          check-latest: false
      - name: Build with Maven
        run: mvn -B install
